package infraestrutura.bean.enumeration;

/**
 * Controle da operação atual da caderneta.
 * CADASTRAR, REGISTRAR_DEVOLUCAO_PROFESSOR, REGISTRAR_RETIRADA_COORDENADOR, REGISTRAR_DEVOLUCAO_COORDENADOR.
 */
public enum OperacaoCaderneta {
	CADASTRAR, REGISTRAR_DEVOLUCAO_PROFESSOR, REGISTRAR_RETIRADA_COORDENADOR, REGISTRAR_DEVOLUCAO_COORDENADOR;
}
